//! Structured rule documentation and the Markdown generator behind
//! `konform rule --explain` and the published docs site.
//!
//! Every rule describes itself through [`Rule::docs`]; everything that can be
//! derived from the rule itself (code, name, config table, fix availability
//! and safety, default state) is read from the [`Rule`] trait, so the prose
//! and the behaviour can't drift apart. `konform generate-docs <DIR>`
//! writes one page per rule plus the rules index and the default-rules page;
//! `docs/rules/` is kept in sync by an integration test.

use super::Rule;
use std::fmt::Write as _;
use std::path::Path;

/// Prose and examples a rule contributes to its documentation page.
#[derive(Debug, Clone, Default)]
pub struct RuleDocs {
    /// Markdown for the "What it does" section.
    pub what_it_does: &'static str,
    /// Markdown for the "Why is this bad?" section.
    pub why_bad: &'static str,
    /// The primary bad/good example.
    pub example: Option<Example>,
    /// Further sections (fix behaviour, exemptions, ...), rendered in order.
    pub sections: Vec<DocSection>,
    /// Options of the rule's config table.
    pub options: Vec<RuleOption>,
}

/// A bad snippet and its corrected counterpart (Python).
#[derive(Debug, Clone)]
pub struct Example {
    pub bad: &'static str,
    pub good: &'static str,
}

/// An extra titled Markdown section.
#[derive(Debug, Clone)]
pub struct DocSection {
    pub title: &'static str,
    /// Markdown body; may contain fenced code blocks.
    pub body: &'static str,
}

/// One option of a rule's `[tool.konform.lint.<config-name>]` table.
#[derive(Debug, Clone)]
pub struct RuleOption {
    pub name: &'static str,
    pub ty: &'static str,
    /// Rendered default, taken from the rule's settings struct.
    pub default: String,
    pub description: &'static str,
}

/// Code shown for `rule`: the category prefix for rules whose codes come from
/// user configuration (KPT), the rule code otherwise.
fn display_code<R: Rule + ?Sized>(rule: &R) -> String {
    if rule.gates_per_violation() {
        format!("{}*", rule.category())
    } else {
        rule.code().to_owned()
    }
}

/// File stem of the rule's page, e.g. `kis001` or `kpt`.
fn slug<R: Rule + ?Sized>(rule: &R) -> String {
    if rule.gates_per_violation() {
        rule.category().to_lowercase()
    } else {
        rule.code().to_lowercase()
    }
}

fn fix_line<R: Rule + ?Sized>(rule: &R) -> Option<&'static str> {
    match (rule.fixable(), rule.is_unsafe_fix()) {
        (false, _) => None,
        (true, false) => Some("Fix is available."),
        (true, true) => {
            Some("Fix is available, but **unsafe**: it is only applied with `--unsafe-fixes`.")
        }
    }
}

const GENERATED: &str = "<!-- Generated by `konform generate-docs`. Do not edit. -->\n\n";

/// The Markdown page for `rule`; also printed by `konform rule --explain`.
pub fn render_rule_page<R: Rule + ?Sized>(rule: &R) -> String {
    let docs = rule.docs();
    let mut out = String::from(GENERATED);
    let _ = writeln!(out, "# {} ({})\n", rule.config_name(), display_code(rule));
    let _ = writeln!(out, "**{}**\n", rule.name());
    if let Some(fix) = fix_line(rule) {
        let _ = writeln!(out, "{fix}\n");
    }
    if rule.enabled_by_default() {
        out.push_str("This rule is enabled by default.\n\n");
    }
    let _ = writeln!(out, "## What it does\n\n{}\n", docs.what_it_does.trim());
    if !docs.why_bad.trim().is_empty() {
        let _ = writeln!(out, "## Why is this bad?\n\n{}\n", docs.why_bad.trim());
    }
    if let Some(ex) = &docs.example {
        let _ = writeln!(
            out,
            "## Example\n\n```python\n{}\n```\n\nUse instead:\n\n```python\n{}\n```\n",
            ex.bad.trim_end(),
            ex.good.trim_end(),
        );
    }
    for section in &docs.sections {
        let _ = writeln!(out, "## {}\n\n{}\n", section.title, section.body.trim());
    }
    let _ = writeln!(
        out,
        "## Options\n\nConfigured in `[tool.konform.lint.{}]`.\n",
        rule.config_name()
    );
    if docs.options.is_empty() {
        out.push_str("This rule has no options.\n\n");
    } else {
        out.push_str("| Option | Type | Default | Description |\n| --- | --- | --- | --- |\n");
        for opt in &docs.options {
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {} | {} |",
                opt.name,
                opt.ty.replace('|', "\\|"),
                opt.default,
                opt.description,
            );
        }
        out.push('\n');
    }
    let _ = write!(
        out,
        "## Suppression\n\n```python\n\
         x = 1  # noqa: {code}\n\
         x = 1  # noqa: {cat}  (every {cat}* rule)\n\
         ```\n",
        code = rule.code(),
        cat = rule.category(),
    );
    out
}

fn sorted(rules: &[Box<dyn Rule>]) -> Vec<&dyn Rule> {
    let mut v: Vec<&dyn Rule> = rules.iter().map(|r| &**r).collect();
    v.sort_by_key(|r| (r.category().to_owned(), r.code().to_owned()));
    v
}

fn status<R: Rule + ?Sized>(rule: &R) -> String {
    let mut parts = Vec::new();
    if rule.enabled_by_default() {
        parts.push("✅");
    }
    if rule.fixable() {
        parts.push("🛠️");
    }
    if rule.is_unsafe_fix() {
        parts.push("⚠️");
    }
    parts.join(" ")
}

const LEGEND: &str = "\
## Legend

- ✅: enabled by default
- 🛠️: the rule has an auto-fix (`--fix`)
- ⚠️: the fix is unsafe and needs `--unsafe-fixes`
";

/// The rules index: one table of every rule, ordered by prefix, then code.
pub fn render_index(rules: &[Box<dyn Rule>]) -> String {
    let mut out = format!(
        "{GENERATED}# Rules\n\n\
         konform supports an increasing list of opinionated rules not supported by Ruff. \
         List them, including your project's own `KPT` patterns, with `konform rule --list`; \
         read one with `konform rule --explain <CODE>`.\n\n\
         {LEGEND}\n\
         | Code | Rule | Linter | Status |\n| ---- | ---- | ------ | ------ |\n",
    );
    for r in sorted(rules) {
        let _ = writeln!(
            out,
            "| `{}` | [`{}`]({}.md)<br>{} | {} ({}) | {} |",
            display_code(r),
            r.config_name(),
            slug(r),
            r.description(),
            r.category_title(),
            r.category(),
            status(r),
        );
    }
    out.push_str(
        "\nCodes are prefix-matched in `select`, `ignore`, `per-file-ignores` and `# noqa`: \
         `KIS` means every `KIS*` rule.\n",
    );
    out
}

/// The default-rules page: what runs when `select` is empty, one section per
/// category prefix.
pub fn render_default(rules: &[Box<dyn Rule>]) -> String {
    let mut out = format!(
        "{GENERATED}# Default rules\n\n\
         konform enables the following rules by default (when no `select` is configured). \
         See [Configuration](../configuration.md) to change that.\n"
    );
    let mut current = "";
    for r in sorted(rules).into_iter().filter(|r| r.enabled_by_default()) {
        if r.category() != current {
            current = r.category();
            let _ = write!(out, "\n## {} ({})\n\n", r.category_title(), current);
        }
        let _ = writeln!(
            out,
            "- [`{}`]({}.md) (`{}`)",
            r.config_name(),
            slug(r),
            display_code(r),
        );
    }
    out
}

/// Write the whole generated rules section into `dir`.
pub fn generate(rules: &[Box<dyn Rule>], dir: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(dir)?;
    std::fs::write(dir.join("index.md"), render_index(rules))?;
    std::fs::write(dir.join("default.md"), render_default(rules))?;
    for rule in rules {
        std::fs::write(
            dir.join(format!("{}.md", slug(&**rule))),
            render_rule_page(&**rule),
        )?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::module_probe::ModuleProbe;
    use crate::rules::{all_rules, FileContext};
    use crate::types::Violation;
    use std::sync::Arc;

    fn rules() -> Vec<Box<dyn Rule>> {
        all_rules(Arc::new(ModuleProbe::default()), None)
    }

    fn page(code: &str) -> String {
        let all = rules();
        let rule = all.iter().find(|r| r.code() == code).expect("rule");
        render_rule_page(&**rule)
    }

    /// A rule that relies on every default (no docs, no fix, no options).
    struct Bare;

    impl Rule for Bare {
        fn code(&self) -> &str {
            "ZZZ001"
        }
        fn category(&self) -> &str {
            "ZZZ"
        }
        fn config_name(&self) -> &str {
            "bare"
        }
        fn name(&self) -> &str {
            "Bare"
        }
        fn description(&self) -> &str {
            "Does nothing."
        }
        fn enabled_by_default(&self) -> bool {
            false
        }
        fn check(&self, _ctx: &FileContext, _cfg: &toml::Value) -> Vec<Violation> {
            Vec::new()
        }
    }

    #[test]
    fn unsafe_fix_rule_page_has_every_section() {
        let page = page("KIS002");
        for needle in [
            "# import-alias-policy (KIS002)",
            "Fix is available, but **unsafe**",
            "This rule is enabled by default.",
            "## What it does",
            "## Why is this bad?",
            "## Example",
            "Use instead:",
            "## Fix behavior",
            "## Options",
            "Configured in `[tool.konform.lint.import-alias-policy]`.",
            "| `alias-template` | `str` | unset |",
            "## Suppression",
            "x = 1  # noqa: KIS002",
            "x = 1  # noqa: KIS  (every KIS* rule)",
        ] {
            assert!(page.contains(needle), "{needle} missing in:\n{page}");
        }
        assert!(page.starts_with(GENERATED));
    }

    #[test]
    fn safe_fix_rule_page_mentions_a_plain_fix() {
        let page = page("KIS001");
        assert!(page.contains("\nFix is available.\n"), "{page}");
        assert!(
            page.contains("`\"warning\" \\| \"error\"`"),
            "pipes are escaped: {page}"
        );
    }

    #[test]
    fn pattern_rule_is_documented_by_its_prefix() {
        let all = rules();
        let kpt = all.iter().find(|r| r.gates_per_violation()).expect("KPT");
        assert_eq!(display_code(&**kpt), "KPT*");
        assert_eq!(slug(&**kpt), "kpt");
        assert!(render_rule_page(&**kpt)
            .starts_with(&format!("{GENERATED}# user-defined-patterns (KPT*)")));
    }

    #[test]
    fn rule_without_docs_gets_minimal_page() {
        let page = render_rule_page(&Bare);
        assert!(page.contains("This rule has no options."), "{page}");
        assert!(
            !page.contains("Why is this bad?") && !page.contains("## Example"),
            "{page}"
        );
        assert!(
            !page.contains("enabled by default") && !page.contains("Fix is available"),
            "{page}"
        );
        assert_eq!(Bare.category_title(), "ZZZ");
        assert!(Bare.explain().contains("# bare (ZZZ001)"));
    }

    #[test]
    fn status_combines_default_fix_and_unsafe_markers() {
        let all = rules();
        let status_of = |code: &str| status(&**all.iter().find(|r| r.code() == code).unwrap());
        assert_eq!(status_of("KIS001"), "✅ 🛠️");
        assert_eq!(status_of("KIS002"), "✅ 🛠️ ⚠️");
        assert_eq!(status(&Bare), "");
    }

    #[test]
    fn index_lists_every_rule_by_prefix_then_code() {
        let index = render_index(&rules());
        let pos = |needle: &str| {
            index
                .find(needle)
                .unwrap_or_else(|| panic!("{needle}:\n{index}"))
        };
        assert!(pos("| `KIS001` |") < pos("| `KIS002` |"));
        assert!(pos("| `KIS002` |") < pos("| `KPT*` |"));
        assert!(
            index.contains("## Legend") && index.contains("[`module-only-imports`](kis001.md)")
        );
        assert!(index.contains("Import style (KIS)"));
    }

    #[test]
    fn default_page_has_one_section_per_prefix_and_skips_disabled_rules() {
        let mut all = rules();
        all.push(Box::new(Bare));
        let page = render_default(&all);
        assert!(
            page.contains(
                "## Import style (KIS)\n\n- [`module-only-imports`](kis001.md) (`KIS001`)"
            ),
            "{page}"
        );
        assert!(page.contains("## User-defined patterns (KPT)"), "{page}");
        assert!(
            !page.contains("ZZZ"),
            "disabled rules are not listed: {page}"
        );
    }

    #[test]
    fn generate_writes_index_default_and_one_page_per_rule() {
        let dir = tempfile::tempdir().unwrap();
        generate(&rules(), &dir.path().join("rules")).unwrap();
        for file in ["index.md", "default.md", "kis001.md", "kis002.md", "kpt.md"] {
            assert!(dir.path().join("rules").join(file).is_file(), "{file}");
        }
    }
}
