//! Structured rule documentation and the Markdown generator behind
//! `konform rule --explain` and the published docs site.
//!
//! Every rule describes itself through [`Rule::docs`]; everything that can be
//! derived from the rule itself (code, name, config table, fix availability
//! and safety, default state) is read from the [`Rule`] trait, so the prose
//! and the behaviour can't drift apart. `konform rule --generate-docs <DIR>`
//! writes one page per rule plus the rules index and the default-rules page;
//! `docs/rules/` is kept in sync by an integration test.

use super::Rule;
use std::fmt::Write as _;
use std::path::Path;

/// Prose and examples a rule contributes to its documentation page.
#[derive(Debug, Clone, Default)]
pub struct RuleDocs {
    /// Markdown for the "What it does" section.
    pub what_it_does: &'static str,
    /// Markdown for the "Why is this bad?" section.
    pub why_bad: &'static str,
    /// The primary bad/good example.
    pub example: Option<Example>,
    /// Further sections (fix behaviour, exemptions, ...), rendered in order.
    pub sections: Vec<DocSection>,
    /// Options of the rule's config table.
    pub options: Vec<RuleOption>,
}

/// A bad snippet and its corrected counterpart (Python).
#[derive(Debug, Clone)]
pub struct Example {
    pub bad: &'static str,
    pub good: &'static str,
}

/// An extra titled Markdown section.
#[derive(Debug, Clone)]
pub struct DocSection {
    pub title: &'static str,
    /// Markdown body; may contain fenced code blocks.
    pub body: &'static str,
}

/// One option of a rule's `[tool.konform.lint.<config-name>]` table.
#[derive(Debug, Clone)]
pub struct RuleOption {
    pub name: &'static str,
    pub ty: &'static str,
    /// Rendered default, taken from the rule's settings struct.
    pub default: String,
    pub description: &'static str,
}

/// Code shown for `rule`: the category prefix for rules whose codes come from
/// user configuration (KPT), the rule code otherwise.
fn display_code<R: Rule + ?Sized>(rule: &R) -> String {
    if rule.gates_per_violation() {
        format!("{}*", rule.category())
    } else {
        rule.code().to_owned()
    }
}

/// File stem of the rule's page, e.g. `kis001` or `kpt`.
fn slug<R: Rule + ?Sized>(rule: &R) -> String {
    if rule.gates_per_violation() {
        rule.category().to_lowercase()
    } else {
        rule.code().to_lowercase()
    }
}

fn fix_line<R: Rule + ?Sized>(rule: &R) -> Option<&'static str> {
    match (rule.fixable(), rule.is_unsafe_fix()) {
        (false, _) => None,
        (true, false) => Some("Fix is available."),
        (true, true) => {
            Some("Fix is available, but **unsafe**: it is only applied with `--unsafe-fixes`.")
        }
    }
}

const GENERATED: &str = "<!-- Generated by `konform rule --generate-docs`. Do not edit. -->\n\n";

/// The Markdown page for `rule`; also printed by `konform rule --explain`.
pub fn render_rule_page<R: Rule + ?Sized>(rule: &R) -> String {
    let docs = rule.docs();
    let mut out = String::from(GENERATED);
    let _ = writeln!(out, "# {} ({})\n", rule.config_name(), display_code(rule));
    let _ = writeln!(out, "**{}**\n", rule.name());
    if let Some(fix) = fix_line(rule) {
        let _ = writeln!(out, "{fix}\n");
    }
    if rule.enabled_by_default() {
        out.push_str("This rule is enabled by default.\n\n");
    }
    let _ = writeln!(out, "## What it does\n\n{}\n", docs.what_it_does.trim());
    if !docs.why_bad.trim().is_empty() {
        let _ = writeln!(out, "## Why is this bad?\n\n{}\n", docs.why_bad.trim());
    }
    if let Some(ex) = &docs.example {
        let _ = writeln!(
            out,
            "## Example\n\n```python\n{}\n```\n\nUse instead:\n\n```python\n{}\n```\n",
            ex.bad.trim_end(),
            ex.good.trim_end(),
        );
    }
    for section in &docs.sections {
        let _ = writeln!(out, "## {}\n\n{}\n", section.title, section.body.trim());
    }
    let _ = writeln!(
        out,
        "## Options\n\nConfigured in `[tool.konform.lint.{}]`.\n",
        rule.config_name()
    );
    if docs.options.is_empty() {
        out.push_str("This rule has no options.\n\n");
    } else {
        out.push_str("| Option | Type | Default | Description |\n| --- | --- | --- | --- |\n");
        for opt in &docs.options {
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {} | {} |",
                opt.name,
                opt.ty.replace('|', "\\|"),
                opt.default,
                opt.description,
            );
        }
        out.push('\n');
    }
    let _ = write!(
        out,
        "## Suppression\n\n```python\n\
         x = 1  # noqa: {code}\n\
         x = 1  # noqa: {cat}  (every {cat}* rule)\n\
         ```\n",
        code = rule.code(),
        cat = rule.category(),
    );
    out
}

fn sorted(rules: &[Box<dyn Rule>]) -> Vec<&dyn Rule> {
    let mut v: Vec<&dyn Rule> = rules.iter().map(|r| &**r).collect();
    v.sort_by_key(|r| (r.category().to_owned(), r.code().to_owned()));
    v
}

fn status<R: Rule + ?Sized>(rule: &R) -> String {
    let mut parts = Vec::new();
    if rule.enabled_by_default() {
        parts.push("✅");
    }
    if rule.fixable() {
        parts.push("🛠️");
    }
    if rule.is_unsafe_fix() {
        parts.push("⚠️");
    }
    parts.join(" ")
}

const LEGEND: &str = "\
## Legend

- ✅ — enabled by default
- 🛠️ — the rule has an auto-fix (`--fix`)
- ⚠️ — the fix is unsafe and needs `--unsafe-fixes`
";

/// The rules index: one table of every rule, ordered by prefix, then code.
pub fn render_index(rules: &[Box<dyn Rule>]) -> String {
    let mut out = format!(
        "{GENERATED}# Rules\n\n\
         konform supports an increasing list of opinionated rules not supported by Ruff. \
         List them, including your project's own `KPT` patterns, with `konform rule --list`; \
         read one with `konform rule --explain <CODE>`.\n\n\
         {LEGEND}\n\
         | Code | Rule | Linter | Status |\n| ---- | ---- | ------ | ------ |\n",
    );
    for r in sorted(rules) {
        let _ = writeln!(
            out,
            "| `{}` | [`{}`]({}.md)<br>{} | {} ({}) | {} |",
            display_code(r),
            r.config_name(),
            slug(r),
            r.description(),
            r.category_title(),
            r.category(),
            status(r),
        );
    }
    out.push_str(
        "\nCodes are prefix-matched in `select`, `ignore`, `per-file-ignores` and `# noqa`: \
         `KIS` means every `KIS*` rule.\n",
    );
    out
}

/// The default-rules page: what runs when `select` is empty, one section per
/// category prefix.
pub fn render_default(rules: &[Box<dyn Rule>]) -> String {
    let mut out = format!(
        "{GENERATED}# Default rules\n\n\
         konform enables the following rules by default (when no `select` is configured). \
         See [Configuration](../configuration.md) to change that.\n"
    );
    let mut current = "";
    for r in sorted(rules).into_iter().filter(|r| r.enabled_by_default()) {
        if r.category() != current {
            current = r.category();
            let _ = write!(out, "\n## {} ({})\n\n", r.category_title(), current);
        }
        let _ = writeln!(
            out,
            "- [`{}`]({}.md) (`{}`)",
            r.config_name(),
            slug(r),
            display_code(r),
        );
    }
    out
}

/// Write the whole generated rules section into `dir`.
pub fn generate(rules: &[Box<dyn Rule>], dir: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(dir)?;
    std::fs::write(dir.join("index.md"), render_index(rules))?;
    std::fs::write(dir.join("default.md"), render_default(rules))?;
    for rule in rules {
        std::fs::write(
            dir.join(format!("{}.md", slug(&**rule))),
            render_rule_page(&**rule),
        )?;
    }
    Ok(())
}
