default_install_hook_types:
  - pre-commit
  - commit-msg

default_stages:
  - pre-commit

repos:
  - repo: local
    hooks:
      - id: format
        name: Code format
        language: system
        entry: cargo fmt
        pass_filenames: false
        verbose: false
      - id: check
        name: Cargo check
        language: system
        entry: cargo check
        pass_filenames: false
        verbose: false

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
