//! Generates the CLI and environment-variable reference pages from the clap
//! definitions in [`crate::cli`], so the docs can't drift from `--help`.
//!
//! Descriptions come from the doc comments on the argument structs; defaults,
//! value names, possible values and `env` bindings are read from clap itself.
//! Run through `konform generate-docs <DIR>`; `docs/reference/` is kept in
//! sync by an integration test.

use clap::{Arg, Command, CommandFactory};
use std::fmt::Write as _;
use std::path::Path;

use crate::cli::Cli;

const GENERATED: &str = "<!-- Generated by `konform generate-docs`. Do not edit. -->\n\n";

/// Environment variables the code reads outside of clap's `env` bindings.
const EXTRA_ENV: &[(&str, &str)] = &[
    (
        "NO_COLOR",
        "When set, disables colour in `--color auto` mode ([no-color.org](https://no-color.org)).",
    ),
    (
        "TERM",
        "`TERM=dumb` disables colour in `--color auto` mode.",
    ),
];

fn built() -> Command {
    let mut cmd = Cli::command();
    cmd.build();
    cmd
}

/// Escape a string for use inside a Markdown table cell.
fn cell(text: &str) -> String {
    text.trim()
        .split("\n\n")
        .map(|p| p.split_whitespace().collect::<Vec<_>>().join(" "))
        .collect::<Vec<_>>()
        .join("<br><br>")
        .replace('|', "\\|")
}

fn visible_args(cmd: &Command) -> impl Iterator<Item = &Arg> {
    cmd.get_arguments()
        .filter(|a| !a.is_hide_set() && !matches!(a.get_id().as_str(), "help" | "version"))
}

fn takes_value(arg: &Arg) -> bool {
    arg.get_num_args().is_some_and(|n| n.takes_values())
}

fn value_name(arg: &Arg) -> String {
    arg.get_value_names()
        .and_then(|v| v.first())
        .map_or_else(|| arg.get_id().as_str().to_uppercase(), |v| v.to_string())
}

/// `-s, --long <VALUE>` for options, `<VALUE>...` for positionals.
fn label(arg: &Arg) -> String {
    if arg.is_positional() {
        let many = arg.get_num_args().is_some_and(|n| n.max_values() > 1);
        return format!("`<{}>{}`", value_name(arg), if many { "..." } else { "" });
    }
    let mut flags = Vec::new();
    if let Some(s) = arg.get_short() {
        flags.push(format!("-{s}"));
    }
    if let Some(l) = arg.get_long() {
        flags.push(format!("--{l}"));
    }
    let mut out = flags.join(", ");
    if takes_value(arg) {
        let _ = write!(out, " <{}>", value_name(arg));
    }
    format!("`{out}`")
}

fn description(arg: &Arg) -> String {
    let help = arg
        .get_long_help()
        .or_else(|| arg.get_help())
        .map(ToString::to_string)
        .unwrap_or_default();
    let mut out = cell(&help);

    let possible: Vec<_> = arg
        .get_possible_values()
        .into_iter()
        .filter(|v| !v.is_hide_set())
        .collect();
    if !possible.is_empty() && takes_value(arg) {
        if possible.iter().any(|v| v.get_help().is_some()) {
            out.push_str("<br><br>");
            let items: Vec<String> = possible
                .iter()
                .map(|v| match v.get_help() {
                    Some(h) => format!("• `{}`: {}", v.get_name(), cell(&h.to_string())),
                    None => format!("• `{}`", v.get_name()),
                })
                .collect();
            out.push_str(&items.join("<br>"));
        } else {
            let names: Vec<String> = possible
                .iter()
                .map(|v| format!("`{}`", v.get_name()))
                .collect();
            let _ = write!(out, "<br><br>Possible values: {}", names.join(", "));
        }
    }
    if takes_value(arg) {
        let defaults: Vec<String> = arg
            .get_default_values()
            .iter()
            .map(|d| format!("`{}`", d.to_string_lossy()))
            .collect();
        if !defaults.is_empty() {
            let _ = write!(out, "<br><br>Default: {}", defaults.join(", "));
        }
    }
    if let Some(env) = arg.get_env() {
        let _ = write!(
            out,
            "<br><br>Environment variable: `{}`",
            env.to_string_lossy()
        );
    }
    out
}

/// The heading an argument is listed under. Arguments without one go under
/// `default_heading`; the generic "Global options" heading is swapped for it
/// too, since that section is already titled that way.
fn heading_of<'a>(arg: &'a Arg, default_heading: &'a str) -> &'a str {
    match arg.get_help_heading() {
        Some("Global options") | None => default_heading,
        Some(h) => h,
    }
}

/// Option tables for `args`, one per `help_heading` in order of appearance.
fn render_args(args: &[&Arg], base_level: usize, default_heading: &str, out: &mut String) {
    let mut headings: Vec<&str> = Vec::new();
    for a in args {
        let h = heading_of(a, default_heading);
        if !headings.contains(&h) {
            headings.push(h);
        }
    }
    let hashes = "#".repeat(base_level);
    for heading in headings {
        let group: Vec<&&Arg> = args
            .iter()
            .filter(|a| heading_of(a, default_heading) == heading)
            .collect();
        let _ = writeln!(out, "{hashes} {heading}\n");
        out.push_str("| Option | Description |\n| ------ | ----------- |\n");
        for a in group {
            let _ = writeln!(out, "| {} | {} |", label(a), description(a));
        }
        out.push('\n');
    }
}

fn usage(cmd: &Command) -> String {
    let mut c = cmd.clone();
    c.render_usage()
        .to_string()
        .trim_start_matches("Usage: ")
        .to_owned()
}

fn about(cmd: &Command) -> String {
    cmd.get_long_about()
        .or_else(|| cmd.get_about())
        .map(ToString::to_string)
        .unwrap_or_default()
        .trim()
        .to_owned()
}

/// The CLI reference page.
pub fn render_cli() -> String {
    let root = built();
    let subcommands: Vec<&Command> = root
        .get_subcommands()
        .filter(|s| !s.is_hide_set() && s.get_name() != "help")
        .collect();

    let mut out = format!(
        "{GENERATED}# Command-line interface\n\n{}\n\n",
        about(&root)
    );
    let _ = writeln!(out, "```text\n{}\n```\n", usage(&root));
    out.push_str("| Command | Description |\n| ------- | ----------- |\n");
    for sc in &subcommands {
        let _ = writeln!(
            out,
            "| [`{0}`](#{0}) | {1} |",
            sc.get_name(),
            cell(&about(sc))
        );
    }
    out.push('\n');

    let globals: Vec<&Arg> = visible_args(&root).filter(|a| a.is_global_set()).collect();
    out.push_str("## Global options\n\nAvailable on every command.\n\n");
    render_args(&globals, 3, "General", &mut out);

    for sc in subcommands {
        let _ = writeln!(out, "## {}\n\n{}\n", sc.get_name(), about(sc));
        let _ = writeln!(out, "```text\n{}\n```\n", usage(sc));
        let positionals: Vec<&Arg> = visible_args(sc).filter(|a| a.is_positional()).collect();
        if !positionals.is_empty() {
            out.push_str(
                "### Arguments\n\n| Argument | Description |\n| -------- | ----------- |\n",
            );
            for a in &positionals {
                let _ = writeln!(out, "| {} | {} |", label(a), description(a));
            }
            out.push('\n');
        }
        let options: Vec<&Arg> = visible_args(sc)
            .filter(|a| !a.is_positional() && !a.is_global_set())
            .collect();
        if !options.is_empty() {
            render_args(&options, 3, "Options", &mut out);
        }
    }
    while out.ends_with("\n\n") {
        out.pop();
    }
    out
}

/// The environment-variable reference page.
pub fn render_env() -> String {
    let root = built();
    let mut rows: Vec<(String, String)> = Vec::new();
    let mut commands = vec![&root];
    commands.extend(root.get_subcommands());
    for cmd in commands {
        for arg in visible_args(cmd) {
            if let Some(env) = arg.get_env() {
                let name = env.to_string_lossy().into_owned();
                if rows.iter().all(|(n, _)| *n != name) {
                    let help = arg.get_help().map(ToString::to_string).unwrap_or_default();
                    rows.push((
                        format!("`{name}`"),
                        format!(
                            "Default for `--{}`; the flag takes precedence. {}",
                            arg.get_long().unwrap_or_default(),
                            cell(&help)
                        ),
                    ));
                }
            }
        }
    }
    for (name, desc) in EXTRA_ENV {
        rows.push((format!("`{name}`"), (*desc).to_owned()));
    }

    let mut out = format!(
        "{GENERATED}# Environment variables\n\n| Variable | Effect |\n| -------- | ------ |\n"
    );
    for (name, desc) in rows {
        let _ = writeln!(out, "| {name} | {desc} |");
    }
    out.push_str(
        "\nWith `--color auto` (the default), colour is emitted only when the output is a \
         TTY, `NO_COLOR` is unset and `TERM` is not `dumb`.\n",
    );
    out
}

/// Write the generated CLI reference pages under `docs_dir/reference/`.
pub fn generate(docs_dir: &Path) -> std::io::Result<()> {
    let dir = docs_dir.join("reference");
    std::fs::create_dir_all(&dir)?;
    std::fs::write(dir.join("cli.md"), render_cli())?;
    std::fs::write(dir.join("environment-variables.md"), render_env())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cli_page_lists_commands_options_and_defaults() {
        let page = render_cli();
        for needle in [
            "## check",
            "## rule",
            "`--select <SELECT>`",
            "`-n, --no-cache`",
            "`<FILE_PATHS>...`",
            "Default: `error`",
            "Environment variable: `KONFORM_COLOR`",
            "• `zuul`",
        ] {
            assert!(page.contains(needle), "{needle} missing in:\n{page}");
        }
    }

    #[test]
    fn hidden_items_are_not_documented() {
        let page = render_cli();
        assert!(!page.contains("## generate-docs"), "{page}");
    }

    #[test]
    fn env_page_includes_clap_and_extra_variables() {
        let page = render_env();
        assert!(
            page.contains("`KONFORM_COLOR`") && page.contains("`NO_COLOR`"),
            "{page}"
        );
    }

    #[test]
    fn generate_writes_both_reference_pages() {
        let dir = tempfile::tempdir().unwrap();
        generate(dir.path()).unwrap();
        for page in ["reference/cli.md", "reference/environment-variables.md"] {
            let text = std::fs::read_to_string(dir.path().join(page)).unwrap();
            assert!(text.starts_with(GENERATED), "{page}");
        }
    }

    #[test]
    fn arguments_without_docs_fall_back_gracefully() {
        // Possible values without their own help are listed inline.
        let arg = Arg::new("mode")
            .long("mode")
            .value_parser(["fast", "slow"])
            .default_value("fast")
            .env("KONFORM_TEST_MODE");
        let cmd = Command::new("t").arg(arg.clone());
        let mut cmd = cmd;
        cmd.build();
        let built = cmd.get_arguments().find(|a| a.get_id() == "mode").unwrap();
        let text = description(built);
        assert!(text.contains("Possible values: `fast`, `slow`"), "{text}");
        assert!(text.contains("Default: `fast`"), "{text}");
        assert!(
            text.contains("Environment variable: `KONFORM_TEST_MODE`"),
            "{text}"
        );
        assert_eq!(label(built), "`--mode <MODE>`");
    }

    #[test]
    fn positional_and_flag_labels() {
        let mut cmd = Command::new("t")
            .arg(Arg::new("paths").num_args(1..).required(true))
            .arg(
                Arg::new("verbose")
                    .short('v')
                    .long("verbose")
                    .action(clap::ArgAction::SetTrue),
            );
        cmd.build();
        let paths = cmd.get_arguments().find(|a| a.get_id() == "paths").unwrap();
        let verbose = cmd
            .get_arguments()
            .find(|a| a.get_id() == "verbose")
            .unwrap();
        assert_eq!(label(paths), "`<PATHS>...`");
        assert_eq!(label(verbose), "`-v, --verbose`");
        assert_eq!(description(verbose), "");
    }

    #[test]
    fn table_cells_escape_pipes_and_join_paragraphs() {
        assert_eq!(cell("a | b\nc\n\nd"), "a \\| b c<br><br>d");
    }
}
